### ISSUE TITLE
LXQt volume cheatcode

### ISSUE THREAD

**Issue by EdPhere** [porteux/porteux#10]
The volume=33 cheatcode doesn't work when booting.  The taskbar sound indicator indicates the volume is set at 100%.

**Comment by EdPhere** [comment]
The Volume Control Settings window shows PulseAudio as being selected.  The
settings are the same for sof-hda-dsp HDMI / DisplayPort 1 Output, 2
Output, 3 Output, and Speaker and Headphones.  I don't see any volume
setting for any of them.  No 0, no 33, no 100.

**Comment by porteux** [comment]
Closing this since it's an upstream issue. Feel free to report it in the LXQt Panel issue tracker: https://github.com/lxqt/lxqt-panel/issues
