### ISSUE TITLE
ISO booting

### ISSUE THREAD

**Issue by EdPhere** [porteux/porteux#13]
For Ventoy users this is the grub2 menu that works for me.

`menuentry " PorteuX 0.4 ISO - Cinnamon"  --class slackware   --class icon-porteux2  {

     set iso="/ISOs/PorteuX/porteux-v0.4-lxqt-1.3.0-stable-x86_64.iso"
     set bootparms="volume=33 reboot=cold extramod=/porteux0.4/Modules \
        kmap=us  noload=mate;lxqt"   # cinn"

     search -f $iso --set=root
     loopback loop $iso
     linux (loop)/boot/syslinux/vmlinuz      from=$iso $bootparms
     initrd (loop)/boot/syslinux/initrd.zst
     }`

**Comment by porteux** [comment]
Thanks! :)
