### ISSUE TITLE
Error: cannot find crt1.o

### ISSUE THREAD

**Issue by TheUtopian** [porteux/porteux#14]
Hi again, I'm trying to build neovim with **slpkg**, but it returns error:
```
    Run Build Command(s):/usr/bin/ninja cmTC_641d6 && [1/2] Building C object CMakeFiles/cmTC_641d6.dir/testCCompiler.c.o
    [2/2] Linking C executable cmTC_641d6
    FAILED: cmTC_641d6 
    : && /usr/bin/cc   CMakeFiles/cmTC_641d6.dir/testCCompiler.c.o -o cmTC_641d6   && :
    /usr/bin/ld: cannot find crt1.o: No such file or directory
    /usr/bin/ld: cannot find crti.o: No such file or directory
    collect2: error: ld returned 1 exit status
    ninja: build stopped: subcommand failed.
```
As I understood the multilibs for gcc is missing, I downloaded multilib module from this repo, but it didn't help. Maybe I'm doing something wrong.

**Comment by porteux** [comment]
Which package is not included in PorteuX?

You can build neovim using the slackbuild (having just 05-devel module activated): https://slackbuilds.org/repository/15.0/development/neovim/

**Comment by TheUtopian** [comment]
@porteux, I meant **slpkg** to autoinstall neovim from slackbuilds, because there's a lot of dependencies. I'll try to make module for slpkg but it would be great if you'll include this package in the next release or the app store.

**Comment by porteux** [comment]
Have you tried the appImage? I tried here and it worked: https://github.com/neovim/neovim/releases

I always think that for stand-alone applications the appImage version is a better solution than building from scratch.

**Comment by TheUtopian** [comment]
I've actually done it before but I still want to build "slpkg" module because there's a lot of other apps without appimage and it feels better when installed natively (e.g icons and console access by default).
