### ISSUE TITLE
Windows Installer Broken

### ISSUE THREAD

**Issue by BreadPlus** [porteux/porteux#17]
All versions of Porteux v0.4 have broken Windows installers. Upon attempting to run the program, Windows will respond "This app can't run on your PC." Using compatibility layers does not help, nor does running the program in Powershell.

**Comment by porteux** [comment]
Thanks for reporting this issue. The installer was corrupted indeed. I updated it in the 0.5 branch and you can download it directly from [this link](https://github.com/porteux/porteux/raw/0.5/boot/porteux-installer-for-windows.exe). 

Let me know if this fixes the issue for you.
