### ISSUE TITLE
Getting issue in live mode after clicking Time and Date Manager

### ISSUE THREAD

**Issue by appEnigma** [porteux/porteux#20]
After booting to MATE live desktop and clicking on Time and Date Manager below error is popping up

![image](https://github.com/porteux/porteux/assets/136222192/d48c1409-55e7-44d2-9aab-461d93df7e1a)

After clicking OK the NTP sync is not happening. Is this behaviour correct ?

**Comment by porteux** [comment]
Yeah, I know. I wish this could work but it doesn't even in Slackware (try [here](https://slackware.nl/slackware-live/latest/)), so I guess it's an upstream issue (probably because MATE relies on systemd and we don't use it). 

Gonna try to report in MATE github page.

Thanks!
