### ISSUE TITLE
Porteus-related question

### ISSUE THREAD

**Issue by NeuroArter** [porteux/porteux#21]
_**Hello!**_

Where do you guys get the sources of Porteus OS?
I found only a few unofficial/outdated repositories on github. On porteus.org I can't find the "source code" section...

**Comment by porteux** [comment]
This not Porteus issue track, but PorteuX one. If you have questions related to Porteus I suggest using its forum: [https://forum.porteus.org](https://forum.porteus.org)

Anyway, Porteus source code is not available to the public, while PorteuX is.

**Comment by NeuroArter** [comment]
**_Thank You!_**

I know this is not the place for porteus questions, but I thought it would be a good idea to ask here.

It's strange to me that the porteus source code is so hard to get and it looks like PorteuX is more community-driven than Porteus.

Thanks for the answering again.
