### ISSUE TITLE
Branch 0.5: Cannot compile 001-core because there's no sysvinit.Slackbuild

### ISSUE THREAD

**Issue by TheUtopian** [porteux/porteux#22]
I've found this file here (https://mirror.lyrahosting.com/slackware/slackware64-current/source/a/sysvinit/sysvinit.SlackBuild) but I think it should be included by default.

I'd like to fix it myself but I compiled it with this SlackBuild file and it seems you've been using custom SlackBuild because size of the init file is 53 and it isn't included in the resulting 001-core module.

**Comment by porteux** [comment]
Oops! My bad. It should be fixed now.

Thanks :)
