### ISSUE TITLE
Live iso using Chromium

### ISSUE THREAD

**Issue by ebbi2017** [porteux/porteux#28]
Hallo, I just spotted PorteuX, after having used Porteus for i586 for awhile.
I actually liked that it was 32 bit also. Now PorteuX seems to be x64 only.

After booting up in a VM with 2 GB RAM set, I tried to install Chromium, but both versions needed to compile (while in Porteus the server based version 117 could just be used as a module, only the version 119 needed to be compiled there).
This also fails in PorteuX live iso booted, because sr0 isn't writeable.
In Porteus this was no issue.
I know it's made to be used with USB sticks, but it would be nice to be able to just use the live iso in a VM.
Maybe you could make the Chromium version useable w/o needing to compile it and also make sr0 writeable to use /tmp and activate the module in a live environment.

Thx in advance.

**Comment by porteux** [comment]
Are you using PorteuX stable? Or current?

The stable version of Chromium since 117.x isn't working on any Slackware 15.0 based distro. Take a look here: https://github.com/porteux/porteux/issues/27

**Comment by ebbi2017** [comment]
I'm on current (porteux-v0.7-lxde-0.10.1-current-x86_64.iso).

Now there's the newer developer version left, 121.0.6120.0 dev build.

Thx for fixing the app store link.

Next idea would be to find out how to boot it off Ventoy and even better with writeable img instead of iso file (just like a USB stick, but booting off Ventoy).

**Comment by porteux** [comment]
@ebbi2017, thanks for the suggestion. I managed to add support to Ventoy boot using PorteuX ISOs. Give it a try with this initrd: https://github.com/porteux/porteux/blob/0.8/boot/syslinux/initrd.zst

I'm not sure if it's possible to use Ventoy to boot a writable image. If you know how to do it, could you write me a step by step please?

Thanks!

**Comment by ebbi2017** [comment]
Beautiful, you're a genius, it boots off Ventoy now :)
Whoa it loads so fast on an i5-3xxx off a Samsung FIT USB key, it's amazing.

If Ventoy doesn't boot on some older PCs with obviously 128 GB BIOS boot limit, you need to make a 2nd partition in Ventoy tool above 128 / 137 G(i)B or use a smaller USB device. Using a 2nd partition on a 160 GB HDD or 250 GB USB stick works on Pentium III-M 1200, C2D U7600, i7-960M, while it hangs on all of those PCs w/o that partition.

Regarding the use of writeable img in Ventoy, I just tested one, because the Ventoy site reads it supports iso, img, vhd(x), wim and efi files at least.
So I loaded a Batocera Linux img (Retro gaming w/ RetroArch, EmulationStation GUI + Kodi) some time ago, checked out some Kodi settings, copied some SNES ROMs and saw that the not even altered img has about 200 MB free space, which made it keep the small diffs I made. I didn't even do anything to it.
The img is meant to be flashed to a drive normally.
It should be possible to make the img files bigger with mounting, GPartEd, by using an altered PiShrink script the opposite way or similar.

I'll check out the newest version of Batocera img and also NomadBSD img, FreeDOS 1.3 Lite/Full USB img, as those are some img I know of. With limited free space those may hang at some point, but for a 1st try it's good enough.
Remember to copy instead of moving those, as those are being altered ;)
At least one old Batocera img worked writeable with 200 MB free img space in Ventoy OOTB.
