### ISSUE TITLE
02 Mate problems

### ISSUE THREAD

**Issue by EdPhere** [porteux/porteux#3]
WiFi works but lists the networks in alphabetical sequence rather than strength sequence.

Clicking on an executable .sh file opens it in a text editor.
Right clicking on an executable .sh file does not show bash as an option.
Right clicking on an executable .sh file and choosing Open With Other Application does not show bash as an option.
Assigning AutoRun to the file results in an error:

Error autorunning software
Cannot find the autorun program

**Comment by EdPhere** [comment]
Okay.  In Mate to execute executable .sh files: open Caja (file manager), click on Edit, Preferences, Behavior, under Executable Text Files, set the option to be Ask each time.  :-)

**Comment by EdPhere** [comment]
The extramod= cheatcode does not appear to be working when booting the ISO file.  Required when adding modules to be run with the booted ISO.

**Comment by porteux** [comment]
Thanks for the bug report. Could you try this initrd and check if it fixes the extramod issue? https://we.tl/t-MuIhBanRmt

**Comment by EdPhere** [comment]
That fixes the extramod= cheatcode problem.  

I am posting this from the booted ISO which pulled in the 009-porteus5-compatibility module, the Firefox App module and my Cinnamon DE using the extramod  cheatcode.

Thank you porteux.

**Comment by porteux** [comment]
Nice! It will be available in the next release :)
