### ISSUE TITLE
missing library?

### ISSUE THREAD

**Issue by jobidon** [porteux/porteux#31]
Just came across your project and really like the concept!
I downloaded and ran the KDE stable version (5.23) and have a few comments:

* it is very snappy and loads very fast, but still appears to load ~25% slower than the equivalent porteus KDE version (on the same PC). Could be the memory stick I used, but is that expected? Any idea why? Will the other DE load faster?
* I tried running the Emoji Selector, but I noticed that ibus-ui-emojier segfaults. Do I need to install additional packages for this?
* Similarly, krename also complains that it needs libtag.so. Is that a separate package that I need to install as well?
* I am considering installing it on a SSD and using it as the main OS on a PC. Can the guest account be renamed, or alternatively, can I create a new user account?

thanks for insight!

**Comment by porteux** [comment]
@jobidon, thanks for the feedback!

1. In all tests I conducted KDE in PorteuX is not just faster than Porteus, but much faster. Please make sure you test using the exact same hardware and conditions (Always Fresh to make sure)
2. yes, this shortcut has been removed in the last release (1.1) since it requires huge `ibus` package
3. fixed in 1.1 by adding `taglib` package
4. you can create a new user (in KDE: settings -> users) and copy all files from /home/guest to /home/newuser

I'm closing this issue. Feel free to re-open it if you find your issues have been addressed.

**Comment by TheUtopian** [comment]
@jobidon

> apparently, nano is not included in the package: have you included a different CLI editor (other than vi)?
As far as I know there's no other cli edtiors in PorteuX, It has only basic packages. You can download nano and create module like this: `sudo getpkg nano; sudo txz2xzm nano*`

> I have NOT been able to create a new user with the settings tool while logged in as root (the button has no effect). And the adduser script is not available either. Can I just create a new line in the passwd file?
You can use this to create a new user: `sudo useradd -m username`

> the USB_INSTALLATION.txt file has not been updated and still refers to porteus v4.0 (instead of porteuX v1.x)
Could you please tell where did you find this file, I cannot find it in PorteuX

**Comment by porteux** [comment]
@jobidon

There are no plans to release a 32bit version. The last 32bit-only CPUs have been released 2 decades ago, and we don't have plans to support such old hardware.

I don't recommend sharing changes folder (`changes=` cheatcode) between root and non-root users. I guess the problem you're having is when you boot with a non-root user, right?

Please, try to add a new user using new PorteuX 1.1. On KDE it's super easy, as I told you before.

Regarding `USB_INSTALLATION.txt`, this a Porteus file, not PorteuX.

**Comment by jobidon** [comment]
@TheUtopian @porteux 
thanks for your comments!
* At times, I have to revive old(er) PCs with 32bit CPU. I'll stick to Porteus for those (and PorteuX for the newer ones!)
* I've added nano to my base folder to load it automatically. Thanks for the suggestion
* The USB... file was indeed part of an old installation of porteus: apologies for the confusion
* I've migrated to v1.1 and indeed user creation has been resolved. Thanks!

This is not related to "missing libraries" anymore, but I have a few question about the startup config. I have a storage media with 2 partitions, as per the following diagram:
```
[/dev/sda1 -a FAT32 partition]
  +- EFI
      +-boot
  +- boot
      +- docs
      +- systinux
[/dev/sda2  - a ext4 partition]
  +- boot
      +- docs
      +- syslinux
  +- porteux
      +- base
```
This works fine and the OS is loaded as expected. But I'd like to eliminate one of the 2 `/boot` directories. To that end, I have updated `/EFI/boot/syslinux.cfg` to include one or the other `/boot/syslinux/porteux.cfg` file (from either partition), but in both cases, there is an issue if I remove the other folder (can't access ext4 partition, or missing png file, etc). Do you have an example config file that only requires one of the two `/boot/` folders?

And finally, in my `porteux.cfg`, I am using the cheatcode "from=/dev/sda2" to boot from that partition. It works fine, but I do notice a warning during boot: "couldn't find none. Correct your from= cheatcode." It does NOT seem to affect the loading at all, but makes me wonder if something is wrong. The complete APPEND line is as follows:
```
APPEND from=/mnt/sda2
```
and during boot, before the cheatcode warning, the following message is also displayed: `^ using PorteuX data from /mnt/sda2/porteux`. So it appears to find the path correctly, but still complains about the cheatcode. Any idea what the "couldn't find *none*" error means?

Thanks for your patience as I'm learning the details of this awesome new distro!

**Comment by porteux** [comment]
In your case you only need `EFI` and `boot` folders in the FAT32 partition. The EXT4 partition will have just `porteux` main folder. And you do not need to set the `from=` cheatcode; it should work automatically because everything is in the same storage unit.

For optimal performance, if you're using `changes=` I recommend using `changes=EXIT:`. Not only it's faster, but it demands less from your storage unit because it only saves the changes once during reboot/shutdown. The only drawback is that if your system hangs or if there is a power cut, you will lose your current session changes.

**Comment by jobidon** [comment]
thanks again: I removed the from= code and it boots fine, as you predicted.
I still have the warning, in yellow: `couldn't find none. Correct your from= cheatcode.` whether the from= code is present or not. It doesn't seem to affect the system, but should it be resolved?

**Comment by porteux** [comment]
Have you removed your porteux/rootcopy folder? This is a known tiny issue: when rootcopy folder is not present, initrd shows this yellow warning. Absolutely not harmful, but I may take a look.
