### ISSUE TITLE
app store minor improvement

### ISSUE THREAD

**Issue by jobidon** [porteux/porteux#32]
The scripts invoked when launching the app-store create the target output module in `$OUTPUTDIR="$PORTDIR/modules"`. If that folder is not accessible (renamed, deleted, etc), the modules are not saved at all, and the temp copy in /tmp/ is also deleted at the end of the script, despite the dialog message stating otherwise.
I suggest the following solutions:
* allow the user to specify the output directory when starting the app-store; and/or
* the app-store should make sure the folder exists when a download is triggered; and/or 
* the module-builder shell script could create the output folder if it is not already present.

**Comment by porteux** [comment]
@jobidon, this is already being done, but there was a bug indeed. It should be working now.

The behavior is that if the output path is not writable (or doesn't exist) the module will be placed in `/tmp`
