### ISSUE TITLE
chkufsd missing?

### ISSUE THREAD

**Issue by tabularasa138** [porteux/porteux#39]
I must be dumb, or missing something.  I'm using porteux-v1.4-cinnamon-6.2.0-current-x86_64.iso.  Release notes fir 1.4 say "5. Added chkufsd to properly fix NTFS partitions".  I cannot find chkufsd anywhere on the filesystem.

**Comment by porteux** [comment]
There's an issue when trying to use it after boot, indeed. It's already fixed and will be released soon in 1.5.

In the meantime, you can use it during boot with cheatcode `fsck`.

Thanks for reporting!
