### ISSUE TITLE
Add support for broadcom wifi

### ISSUE THREAD

**Issue by sattheptonghop** [porteux/porteux#41]
How to install broadcom wifi driver?

**Comment by porteux** [comment]
Try to build this (remember to have both `05-devel` and `06-crippled_sources` modules activated): https://slackbuilds.org/repository/15.0/network/broadcom-wl/

After building it, go to your `/tmp` folder, convert the .txz file to .xzm and copy it to `/porteux/modules` and finally reboot.

Let us know if it works for you so we can close this issue.

**Comment by sattheptonghop** [comment]
do this wifi ok. must download  [libffi.so.7](https://packages.slackware.com/?r=slackware64-15.0&p=libffi-3.3-x86_64-3.txz) and [libunistring.so.2 ](https://packages.slackware.com/?r=slackware64-15.0&p=libunistring-0.9.10-x86_64-3.txz) for make build

**Comment by porteux** [comment]
Great! I guess you're using PorteuX stable, not current, right?

Do you mind testing something? Could you moving out from porteux/modules the new driver you compiled and remove the 2 .conf files in `/etc/modprobe.d/` and reboot? There's a chance your wifi might work without the new driver.

Let me know. Thanks!

**Comment by sattheptonghop** [comment]
yes, i using stable. And now i install current lxqt 20240828, edit 2 .conf
in /etc/modprobe.d with blank file. savechange to modules. then reboot.
then drive wifi not work.

Vào 21:01, Th 7, 21 thg 9, 2024 PorteuX ***@***.***> đã viết:

**Comment by fulalas** [comment]
I see. Thanks for the test!
