### ISSUE TITLE
Support for Steam Deck

### ISSUE THREAD

**Issue by sadatdaniel** [porteux/porteux#42]
Dear developer, I've been trying out PorteuX on the Steam Deck using the latest GNOME 47.1 build. It boots smoothly from the SD card, it's fast, and the touchscreen works great with the correct display orientation and resolution. However, I'm facing issues with Bluetooth and sound: Bluetooth shows "No devices found," and the sound options only display "dummy output." Additionally, the fans either run at full speed or don’t run at all - there's no in between.  If these issues can be resolved, PorteuX could be an excellent distro for users looking to enhance productivity on the go, all without needing to install it directly on the Deck. Thank you.

**Comment by porteux** [comment]
Can you try [this kernel](https://www.mediafire.com/file/auyq9k0ydq4jo4e/kernel-6.11.4-steamdeck-porteux-2.zip), please?

Don't forget to copy/replace `vmlinuz` to your `boot/syslinux` folder.

Regarding sound, try to change the audio profile from 'auto' to 'sof...' and the audio output to something like 'RAVEN/RAVEN2/FIREFLIGHT/RENOIRAUDIO'.

**Comment by porteux** [comment]
This issue seems abandoned, so I'm closing it.
