### ISSUE TITLE
nano.xzm module from porteus distro ERROR Glibc

### ISSUE THREAD

**Issue by zyrusete** [porteux/porteux#44]
I get this module from the porteus repository, and put into the Modules directory. When I run nano from terminal, i obtain this error message: 

nano.bin: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by nano.bin)

Output of ldd --version reports: ldd (GNU libc) 2.33

**Comment by TheUtopian** [comment]
@zyrusete, you can run this command ```getpkg nano && txz2xzm nano*``` to download and create nano module from Slackware repository. It should work

**Comment by porteux** [comment]
The answer provided by @TheUtopian is the correct one, and since @zyrusete didn't provide any feedback, I'm closing this.

Feel free to ask any questions if you encounter any problems.

Thanks!
