### ISSUE TITLE
Save changes

### ISSUE THREAD

**Issue by EdPhere** [porteux/porteux#6]
Is there a way to save changes when installed on FAT USB sticks?

**Comment by porteux** [comment]
Only using PorteuX Save Session application to save changes in a modules, or in a save.dat file container or a in folder.

Another way would be doing it manually, saving only the files you want using /etc/rc.d/rc.local_shutdown script, but this is a bit tricky as you need to figure out which files you have to save, which will depend on what applications you use and how you use them.
