### ISSUE TITLE
Grub2 menu

### ISSUE THREAD

**Issue by EdPhere** [porteux/porteux#7]
For grub2 users this works as a PorteuX menu icon.

[![porteux.png](https://i.postimg.cc/Xvcsyq38/porteux.png)](https://postimg.cc/KKjP6Z1k)

**Comment by porteux** [comment]
This is Github's logo, not related to PorteuX.

**Comment by EdPhere** [comment]
It's the icon connected to my PorteuX browser bookmarks.  Having it on my
grub menus is a matching visual connection.
