### ISSUE TITLE
LXQt stable problems

### ISSUE THREAD

**Issue by EdPhere** [porteux/porteux#9]
WiFi connections are in alphabetical sequence rather than strength sequence.  Annoying having to scroll to fine desired one.

System shuts down when battery is low without a warning causing lost of work in progress.

**Comment by porteux** [comment]
1- this is not an issue and it seem there's nothing we can do afaik. You can try to report to the developer: https://github.com/palinek/nm-tray/issues

2- this is probably another upstream limitation (i.e. nothing we can do to fix). Maybe you could try the same test using Lubuntu and see if it behaves differently. I don't have any laptop to test at the moment.

**Comment by EdPhere** [comment]
I don't have these problems with Porteus 5.0.
